import pyautogui
import json
import time
from utils.check_spread import init_log_cursor, check_spread_exception
from utils.logger_utils import build_timestamped_log_file, get_logger

###########################################
# 此脚本用于根据生成器脚本生成的坐标列表，
# 在 Minecraft 中预加载指定位置的区块，
# 确保后续截图时能够快速加载。
###########################################
# This script is used to preload blocks at specified locations in Minecraft
# based on a list of coordinates generated by a generator script,
# ensuring that subsequent screenshots load quickly.
###########################################

# 需要手动配置的参数
INPUT_FILE = "./data/capture_list_1_0_0.json"
WAIT_TIME = 1.0

CHECK_SPREAD = True
MC_LOG_PATH = r"...\logs\latest.log"
LOG_SUFFIX = "./logs/maprun"

def send_cmd(cmd):
    pyautogui.press('t')
    pyautogui.write(cmd)
    pyautogui.press('enter')

def run_map():
    logger = get_logger("maprun", build_timestamped_log_file(LOG_SUFFIX), include_console=False)
    spread_cursor = None
    can_check_spread = False

    if CHECK_SPREAD:
        spread_cursor = init_log_cursor(MC_LOG_PATH)
        if spread_cursor is None:
            print(f"Spread check is enabled but MC log file was not found: {MC_LOG_PATH}")
        else:
            can_check_spread = True

    try:
        with open(INPUT_FILE, "r") as f:
            data = json.load(f)
    except FileNotFoundError:
        print("The coordinate list file was NOT found. Please run the generator script first.")
        return
    
    config = data.get("config", {})
    coords = data.get("coords", [])
    enable_y = bool(config.get("enable_y", False))

    print("The map preloading script will start in 5 seconds. Please click into the Minecraft window and ensure the chat bar is closed.")
    time.sleep(5)

    for entry in coords:
        biome_name = entry.get("biome", "Unknown")
        logger.info("Processing data id %s, current biome: %s", entry["id"], biome_name)
        spread_exception_hit = False

        y_value = entry.get("y", None)
        use_exact_y = False
        parsed_y = None

        if enable_y and y_value is not None:
            try:
                parsed_y = int(y_value)
                use_exact_y = True
            except (TypeError, ValueError):
                print(f"Invalid y for id {entry.get('id', 'Unknown')}, y={y_value!r}. This record is skipped.")
                continue

        if use_exact_y:
            send_cmd(f"/tp @s {entry['x']} {parsed_y} {entry['z']} {entry['yaw']} {entry['pitch']}")
        else:
            send_cmd(f"/spreadplayers {entry['x']} {entry['z']} 0 1 false @s")
            if can_check_spread:
                time.sleep(0.2)
                spread_cursor, spread_error = check_spread_exception(MC_LOG_PATH, spread_cursor)
                if spread_error:
                    spread_exception_hit = True
                    logger.warning("Spreadplayers exception for id %s: %s", entry["id"], spread_error)
            send_cmd(f"/tp @s {entry['x']} ~ {entry['z']} {entry['yaw']} {entry['pitch']}")
        
        # 等待区块加载
        time.sleep(WAIT_TIME)

        if CHECK_SPREAD and spread_exception_hit:
            print(f"Data id {entry['id']} processed with spreadplayer exception, please check log file")
        else:
            print(f"Data id {entry['id']} processed successfully.")

    print("All map preloading completed.")

if __name__ == "__main__":
    run_map()