import pyautogui
import json
import time

###########################################
# 此脚本用于根据生成器脚本生成的坐标列表，
# 在 Minecraft 中预加载指定位置的区块，
# 确保后续截图时能够快速加载。
###########################################
# This script is used to preload blocks at specified locations in Minecraft
# based on a list of coordinates generated by a generator script,
# ensuring that subsequent screenshots load quickly.
###########################################

# 需要手动配置的参数
INPUT_FILE = "./data/coords_list_1_0_0.json"
WAIT_TIME = 3.0

def send_cmd(cmd):
    pyautogui.press('t')
    pyautogui.write(cmd)
    pyautogui.press('enter')

def run_map():
    try:
        with open(INPUT_FILE, "r") as f:
            data = json.load(f)
    except FileNotFoundError:
        print("The coordinate list file was NOT found. Please run the generator script first.")
        return
    
    config = data.get("config", {})
    coords = data.get("coords", [])
    enable_y = bool(config.get("enable_Y", False))

    print("The map preloading script will start in 5 seconds. Please click into the Minecraft window and ensure the chat bar is closed.")
    time.sleep(5)

    for entry in coords:
        biome_name = entry.get("biome", "Unknown")
        print(f"Processing data id {entry['id']}, current biome: {biome_name}...")

        if enable_y:
            send_cmd(f"/tp @s {entry['x']} {entry['y']} {entry['z']} {entry['yaw']} {entry['pitch']}")
        else:
            send_cmd(f"/spreadplayers {entry['x']} {entry['z']} 0 1 false @s")
            send_cmd(f"/tp @s {entry['x']} ~ {entry['z']} {entry['yaw']} {entry['pitch']}")
        
        # 等待区块加载
        time.sleep(WAIT_TIME)

        print(f"Data id {entry['id']} processed successfully.")

    print("All map preloading completed.")

if __name__ == "__main__":
    run_map()